### ISSUE TITLE
How do I pass on options to the chart

### ISSUE THREAD

**Issue by akh2013** [bmuschko/grails-google-visualization#44]
Hello,

Happy New Year!

I just started using your plugin.  Thank you for your contribution.

I wish to pass on animation options to the chart.  I tried the following but it fails.  Can you please guide me how to pass on animation options to chart?

animation: { duration: 100 }

<gvisualization:lineCoreChart dynamicLoading="${true}" elementId="linechart" title="Your Marketing Burn"
width="100%" height="${300}" columns="${columns}"  data="${expenses}" options="[animation: [duration: 100 ]]"/>

**Comment by aruizca** [comment]
Hi, we will publish version 1.0 this weekend. I will give you more details about your question then if you don't mind.
Cheers

**Comment by aruizca** [comment]
Hi @akh2013 
Please refer to the basic usage section of the documentation: https://github.com/bmuschko/grails-google-visualization/wiki/usage
You need to use the map notation within an EL expression.
Please use the latest release 1.0
Cheers,

**Comment by akh2013** [comment]
Hi,

like this?

legend="${[animation:[duration: 100]]}"

**Comment by aruizca** [comment]
First you need to check the API for the chart you want to use. So imagine you want to use a Line Chart. Then you go to the configuration options and check for the animation option and its type: https://developers.google.com/chart/interactive/docs/gallery/linechart?csw=1#Configuration_Options

To express that you need an attribute in your taglib called animation and to express the duration you use the EL expression since it is an object with different nested config options like duration. In your case it would like something like:
```
animation="${[duration:100]}"
```
I hope it helps
